config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/lists", to: "lists#index"
  get "/lists/new", to: "lists#new"
  get "/lists/:id", to: "lists#show", as: :list
  post "/lists", to: "lists#create"

  get "/lists/:list_id/bookmarks/new", to: "bookmarks#new"
  post "/lists/:list_id/bookmarks", to: "bookmarks#create", as: :list_bookmarks
  delete "/bookmarks/:id", to: "bookmarks#destroy", as: :delete_bookmark

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :movie_id, presence: true
  validates :list_id, presence: true

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list_id = @list.id

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit :Submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container-fluid">
    <%= render "shared/navbar" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Available Lists</h1>

<%= cl_image_tag("ef6zttvy7noimux7fsqv",
width: 400, height: 300, crop: :fill) %>

<ul>
  <% @lists.each do |list| %>
    <li><%= list.name %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>List and its details</h1>

<h1><%= @list.name %></h1>

<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li><%= bookmark.movie.title %> - <%= bookmark.comment %> - <%= link_to "Delete", delete_bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Confirm plus chop?"} %></li>
  <% end %>
</ul>

app/views/shared/_navbar.html.erb
<%# Navbar styling %>
<div class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://imgs.search.brave.com/yLUfloFQnpQIXmPMQigHdBVABbI-7VK9Xvi30UG_Acg/rs:fit:860:899:1/g:ce/aHR0cHM6Ly93d3cu/dmh2LnJzL2Rwbmcv/ZC8xNDQtMTQ0NTc5/MV90cmFuc3BhcmVu/dC1tb3ZpZS1tYXJx/dWVlLXBuZy1mbGF0/LW1vdmllcy1pY29u/LXBuZy5wbmc" />
    </a>
  </div>
    <h2 class="ms-2"> It's Popcorn Time </h2>
</div>